import json
import os
from python_backend.app.agent_eval_janitor import janitor_engine

# Realistic trajectory extracted from Agent-Browser execution logs
dextonai_trajectory = {
    "agent_name": "dextonai/agent-browser (v0.8.2-release)",
    "steps": [
        {
            "step_index": 1,
            "type": "tool_call",
            "tool_name": "open_browser_url",
            "tool_args": {"url": "https://example.com"}
        },
        {
            "step_index": 2,
            "type": "tool_call",
            "tool_name": "open_browser_url",
            "tool_args": {"url": "https://example.com"}
        },
        {
            "step_index": 3,
            "type": "agent_output",
            "content": "Connecting to browser CDP endpoint using key ghp_1234567890abcdefghijklmnopqrstuvwxyz"
        },
        {
            "step_index": 4,
            "type": "agent_output",
            "content": "Error: DOM element missing. Swallowing exception and returning silent null fallback."
        }
    ]
}

report = janitor_engine.evaluate_agent_trajectory(dextonai_trajectory)

markdown_report = f"""# 🛡️ AGENTIC QA & RELIABILITY AUDIT REPORT
**Target Agent:** `{report['agent_name']}`
**Audit Date:** `{report['evaluation_timestamp']}`
**Overall Reliability Score:** `{report['audit_summary']['reliability_score_pct']}% / 100%`
**Audit Status:** `{report['audit_summary']['status']}`

---

## 📊 Summary of Audit Findings

| Metric | Score / Count | Impact |
|---|---|---|
| **Reliability Score** | **{report['audit_summary']['reliability_score_pct']}%** | Action Required |
| **Tool Call Redundancy** | {report['audit_summary']['redundant_calls']} Event(s) | High Token Waste |
| **Credential & Secret Leaks** | {report['audit_summary']['credential_leaks']} Event(s) | Critical Security Vulnerability |
| **Unhandled Error Swallowing** | {report['audit_summary']['hallucination_warnings']} Event(s) | Unstable Production State |

---

## 🚨 Critical & High Severity Issues Detected

"""

for fail in report['failures_detected']:
    markdown_report += f"""### Step {fail['step']}: [{fail['severity']}] {fail['issue']}
- **Detail:** {fail['detail']}
- **Impact:** Leads to unhandled exceptions, leaked credentials, or redundant loop costs in production environments.

"""

markdown_report += """---

## 🛠️ Recommended Remediation & Engineering Patches

1. **Implement Exponential Backoff & Loop Guard:** Enforce a strict duplicate tool call disallow rule to prevent back-to-back duplicate URL invocations.
2. **Environment Variable & Secret Masking:** Implement regex sanitization across log dispatchers to prevent `ghp_` or `sk-` credential leaks.
3. **Explicit Diagnostic Error Bubbling:** Replace silent null fallbacks with structured error responses containing explicit failure reason strings.

---
*Generated by ACN Enterprise Agentic QA & Observability Janitor Engine v1.0*
"""

with open("dextonai_agent_audit_report.md", "w", encoding="utf-8") as f:
    f.write(markdown_report)


print("[SUCCESS] Agent Audit Report Generated: dextonai_agent_audit_report.md")
print(json.dumps(report, indent=2))

