# Bartholomew Security Daemon v3.1 Container Image
FROM golang:1.23

WORKDIR /app

COPY go.mod ./
COPY main.go ./
COPY index.html ./
COPY PITCH_DECK.html ./
COPY founder_avatar.jpg ./
COPY dashboard/ ./dashboard/
COPY demo_trajectory_inspector.html ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o bartholomew_daemon main.go

ENV PORT=8080
EXPOSE 8080

CMD ["./bartholomew_daemon"]
