#!/usr/bin/env python3
"""
Patch script for Issue #1438:
  1. Fix rate_limiting.py: fail-closed on unknown operations
  2. Fix ids.py: align is_valid_memory_id with safe_deletion.py pattern
  3. Fix constants.py: add SourceType validation
"""
import re, sys

# --- Fix 1: rate_limiting.py - fail-closed on unknown operations ---
with open('memanto/app/utils/rate_limiting.py', 'r') as f:
    content = f.read()

old = "        if operation not in self.limits:\n            return True, None"
new = (
    "        if operation not in self.limits:\n"
    "            raise ValueError(\n"
    "                f\"Unknown rate-limit operation '{operation}'. \"\n"
    "                \"Register it in RateLimiter.limits before use.\"\n"
    "            )"
)

if old in content:
    content = content.replace(old, new)
    with open('memanto/app/utils/rate_limiting.py', 'w') as f:
        f.write(content)
    print("FIXED rate_limiting.py: fail-closed on unknown operations")
else:
    print("SKIP rate_limiting.py: pattern not found (already patched?)")

# --- Fix 2: ids.py - align is_valid_memory_id with safe_deletion pattern ---
with open('memanto/app/utils/ids.py', 'r') as f:
    content = f.read()

old_ids = (
    "def is_valid_memory_id(memory_id: str) -> bool:\n"
    "    \"\"\"Validate memory ID format\"\"\"\n"
    "    return bool(memory_id and len(memory_id) > 4 and \"_\" in memory_id)"
)
new_ids = (
    "def is_valid_memory_id(memory_id: str) -> bool:\n"
    "    \"\"\"Validate memory ID format.\n\n"
    "    Accepts IDs generated by ``generate_memory_id`` (``prefix_hex``) as well\n"
    "    as IDs that use hyphens (e.g. ``abc-123``), matching the pattern used by\n"
    "    ``SafeDeletion._is_valid_memory_id`` so that IDs accepted for deletion\n"
    "    are also accepted by general validation.\n"
    "    \"\"\"\n"
    "    import re\n"
    "    if not memory_id or len(memory_id) < 4:\n"
    "        return False\n"
    "    return bool(re.match(r\"^[a-zA-Z0-9_-]+$\", memory_id))"
)

if old_ids in content:
    content = content.replace(old_ids, new_ids)
    with open('memanto/app/utils/ids.py', 'w') as f:
        f.write(content)
    print("FIXED ids.py: aligned is_valid_memory_id with safe_deletion pattern")
else:
    print("SKIP ids.py: pattern not found (already patched?)")

# --- Fix 3: constants.py - SourceType validation ---
with open('memanto/app/constants.py', 'r') as f:
    content = f.read()

old_src = 'SourceType = str  # e.g., "user", "agent", "tool", "system", or specific "agent_name"'
new_src = (
    "# Source Types — the canonical built-in values.\n"
    "# The type annotation remains ``str`` for backwards-compatibility with\n"
    "# free-form agent names, but ``VALID_SOURCE_TYPES`` is the authoritative\n"
    "# list of well-known values and should be used for validation.\n"
    'SourceType = str  # e.g., "user", "agent", "tool", "system", or a specific agent name\n'
    "\n"
    "# The well-known source values that routes/services should validate against.\n"
    "# Custom agent names are still valid; this set covers the built-in ones.\n"
    "KNOWN_SOURCE_TYPES: frozenset[str] = frozenset({\n"
    '    "user",\n'
    '    "agent",\n'
    '    "tool",\n'
    '    "system",\n'
    "})"
)

if old_src in content:
    content = content.replace(old_src, new_src)
    with open('memanto/app/constants.py', 'w') as f:
        f.write(content)
    print("FIXED constants.py: added KNOWN_SOURCE_TYPES for source field validation")
else:
    print("SKIP constants.py: pattern not found (already patched?)")

print("All patches applied.")
