apiVersion: v1
kind: Secret
metadata:
  name: akash-provider-keys
  namespace: akash-services
type: Opaque
data:
  key.txt: LS0tLS1CRUdJTiBURU5ERVJNSU5UIFBSSVZBVEUgS0VZLS0tLS0Ka2RmOiBhcmdvbjIKc2FsdDogRTE5NUE2MzBENEQzNzdEOTNGOUE4NTVERDdBNDU2NDQKdHlwZTogc2VjcDI1NmsxCgp4WU9GTVo5ZkFpQTcwK0tVYWNxWUhIT1hvTElPMFlWL1VHbHJPY3BJMDJ3Yi9qbjlEU3MrUVBjeHdhMTJ0UkR5Cmw5MXdKckk9Cj1WQjl3Ci0tLS0tRU5EIFRFTkRFUk1JTlQgUFJJVkFURSBLRVktLS0tLQo=
  key-pass.txt: cHJvdmlkZXJwYXNz
