"""
Bartholomew Guard for NVIDIA NIM (Inference Microservice)
=========================================================
Integrates Bartholomew Trust Protocol (BTP v5.4) with NVIDIA NIM microservices
(self-hosted GPU containers or hosted endpoints at integrate.api.nvidia.com).

Enforces sub-35us AST safety invariants, Keystone capability passkeys, spend caps,
and cryptographically signed Merkle audit receipts across all NIM tool invocations.
"""

import os
import time
import json
import logging
from typing import Dict, Any, Optional, List, Union, Tuple

from src.polyglot_ast_validator import PolyglotASTValidator
from src.secret_masker import SecretVaultMasker
from src.trust_protocol import BartholomewTrustAuthority
from src.keystone_passkey import KeystoneEngine, KeystonePasskey, KeystoneScope, ClearanceResult

logger = logging.getLogger("btp.nvidia_nim")


class BartholomewNIMGuard:
    """Runtime security interceptor for NVIDIA NIM inference microservices."""

    def __init__(
        self,
        base_url: str = "http://localhost:8000/v1",
        api_key: Optional[str] = None,
        authority: Optional[BartholomewTrustAuthority] = None,
        keystone_engine: Optional[KeystoneEngine] = None,
        spend_cap_usd: float = 100.0,
        enforce_keystone: bool = False
    ):
        self.base_url = os.getenv("NIM_BASE_URL", base_url).rstrip("/")
        self.api_key = api_key or os.getenv("NGC_API_KEY") or os.getenv("NVIDIA_API_KEY")
        self.authority = authority or BartholomewTrustAuthority()
        self.keystone_engine = keystone_engine or KeystoneEngine()
        self.spend_cap_usd = spend_cap_usd
        self.enforce_keystone = enforce_keystone
        self.current_spend_usd = 0.0

    def inspect_prompt_payload(self, messages: List[Dict[str, Any]]) -> Tuple[bool, str]:
        """Scan input prompts for malicious injections or exfiltration attempts."""
        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, str) and content.strip():
                is_safe, reason, _ = PolyglotASTValidator.validate_code(content)
                if not is_safe:
                    return False, f"Prompt invariant violation: {reason}"
        return True, "SAFE"

    def inspect_tool_call(
        self,
        tool_name: str,
        arguments: Union[Dict[str, Any], str],
        passkey: Optional[KeystonePasskey] = None
    ) -> Dict[str, Any]:
        """
        Pre-flight gate for tool calls generated by NVIDIA NIM.
        Enforces Keystone passkeys, AST safety, and mints an Ed25519 receipt.
        """
        t0 = time.perf_counter()

        # 1. Keystone Capability Passkey Check
        if self.enforce_keystone or passkey is not None:
            if passkey is None:
                raise PermissionError("BTP-VETO: Keystone passkey required for NIM tool execution.")
            
            if not self.keystone_engine.verify_signature(passkey):
                raise PermissionError("BTP-VETO: Keystone signature verification failed.")

            clearance = self.keystone_engine.check_clearance(
                passkey=passkey,
                action_type="COMMAND_EXEC",
                target=tool_name
            )
            if clearance.verdict != "ALLOW":
                raise PermissionError(f"BTP-VETO: Keystone capability denied for tool '{tool_name}': {clearance.reason}")

        # 2. AST Invariant Inspection on Tool Arguments
        arg_str = json.dumps(arguments) if isinstance(arguments, dict) else str(arguments)
        is_safe, ast_err, meta = PolyglotASTValidator.validate_code(arg_str)
        if not is_safe:
            raise PermissionError(f"BTP-VETO: Unsafe payload detected in NIM tool '{tool_name}': {ast_err}")

        # 3. Secret Vault Masking
        sanitized_args, redactions, mask_latency = SecretVaultMasker.mask_text(arg_str)

        eval_latency_us = (time.perf_counter() - t0) * 1_000_000

        # 4. Mint Merkle Audit Receipt
        receipt = self.authority.evaluate_intent(
            agent_id=passkey.agent_id if passkey else "nvidia-nim-agent",
            action_type=f"NIM_TOOL_{tool_name.upper()}",
            payload={
                "tool": tool_name,
                "latency_us": eval_latency_us,
                "sanitized": len(redactions) > 0,
                "status": "AUTHORIZED"
            }
        )
        return {
            "authorized": True,
            "latency_us": eval_latency_us,
            "receipt": receipt,
            "sanitized_arguments": sanitized_args
        }

    def intercept_chat_request(
        self,
        request_body: Dict[str, Any],
        passkey: Optional[KeystonePasskey] = None
    ) -> Dict[str, Any]:
        """
        Intercept an OpenAI-compatible /chat/completions payload destined for NIM.
        Verifies prompt safety, spend budget, and stamps pre-flight approval.
        """
        messages = request_body.get("messages", [])
        is_safe, reason = self.inspect_prompt_payload(messages)
        if not is_safe:
            raise PermissionError(f"BTP-VETO: Rejected NIM request. {reason}")

        # Spend check
        model = request_body.get("model", "meta/llama-3.1-8b-instruct")
        estimated_cost = 0.0015
        if self.current_spend_usd + estimated_cost > self.spend_cap_usd:
            raise PermissionError(f"BTP-VETO: Spend cap exceeded (${self.spend_cap_usd} USD)")

        self.current_spend_usd += estimated_cost

        return {
            "status": "APPROVED",
            "model": model,
            "spend_usd": self.current_spend_usd,
            "endpoint": f"{self.base_url}/chat/completions"
        }
