steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deploy/gcp/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/bartolomew-cloud-engine:latest', '.']
images:
  - 'gcr.io/$PROJECT_ID/bartolomew-cloud-engine:latest'
