import { useState } from 'react'
import { Shield, CheckCircle2, Lock, FileCode, Clock, Hash, ExternalLink, Activity } from 'lucide-react'

interface AuditReceipt {
  date: string
  timestamp_utc: string
  merkle_root: string
  ci_suites: string
  conclusion: 'PASS' | 'FAIL'
  tsc_controls: string[]
  iso_controls: string[]
  source_fingerprints: { file: string; sha256: string }[]
}

const HISTORICAL_RECEIPTS: AuditReceipt[] = [
  {
    date: '2026-08-22',
    timestamp_utc: '2026-08-22T07:09:24.391Z',
    merkle_root: '932d9c5d7c0ff73bf8cc5ff06bc810bf105e9544e3fb07d8ab343bfdaa05dc10',
    ci_suites: '18/18 Multi-Runtime Suites Passing (100%)',
    conclusion: 'PASS',
    tsc_controls: ['CC7.1 (Continuous Monitoring)', 'CC7.2 (Log Evaluation)', 'CC9.1 (Risk Assessment)'],
    iso_controls: ['A.8.8 (Vulnerability Mgmt)', 'A.8.30 (Monitoring Activities)', 'A.9.1 (Performance Eval)'],
    source_fingerprints: [
      { file: 'src/btp_guard.py', sha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e' },
      { file: 'src/container_sandbox.py', sha256: 'c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9' },
      { file: 'ci_security_gate.py', sha256: 'a1b2c3d4e5f60718293a4b5c6d7e8f9012345678' }
    ]
  }
]

export default function ContinuousComplianceTimeline() {
  const [selectedReceipt, setSelectedReceipt] = useState<AuditReceipt>(HISTORICAL_RECEIPTS[0])

  return (
    <section id="compliance-timeline" className="py-16 border-t border-[#222222] bg-[#000000]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="w-2 h-2 bg-[#10b981] animate-pulse" />
              <span className="text-[#10b981] text-xs font-mono font-bold tracking-wider">
                [CONTINUOUS COMPLIANCE TELEMETRY]
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold font-sans text-[#ffffff] tracking-tight">
              Automated SOC 2 &amp; ISO 27001 Evidence Timeline
            </h2>
            <p className="text-[#a1a1aa] text-sm mt-1 max-w-2xl font-sans">
              Daily cryptographic Merkle receipts generated by automated GitHub Actions cron jobs (AICPA CC7.1 / ISO 27001 A.8.30).
            </p>
          </div>

          <div className="flex items-center gap-3">
            <a
              href="https://github.com/ivegotahunnitonit/bartholomew/tree/main/audit_evidence"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-[#0a0a0a] border border-[#333333] hover:border-[#10b981] text-xs font-mono text-[#d4d4d8] hover:text-[#ffffff] transition"
            >
              <FileCode className="w-3.5 h-3.5 text-[#10b981]" />
              <span>[RAW AUDIT ARCHIVE]</span>
              <ExternalLink className="w-3 h-3 text-[#71717a]" />
            </a>
          </div>
        </div>

        {/* Evidence Dashboard Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left: Timeline List */}
          <div className="bg-[#0a0a0a] border border-[#222222] p-4 flex flex-col">
            <div className="text-xs font-mono text-[#71717a] uppercase mb-3 flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 text-[#f59e0b]" />
              <span>Daily Receipt Archives</span>
            </div>

            <div className="space-y-2">
              {HISTORICAL_RECEIPTS.map((receipt) => (
                <button
                  key={receipt.date}
                  onClick={() => setSelectedReceipt(receipt)}
                  className={`w-full text-left p-3 border transition flex items-center justify-between font-mono text-xs ${
                    selectedReceipt.date === receipt.date
                      ? 'bg-[#111111] border-[#10b981] text-[#ffffff]'
                      : 'bg-[#000000] border-[#222222] text-[#a1a1aa] hover:border-[#444444]'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <span className="w-2 h-2 rounded-full bg-[#10b981]" />
                    <div>
                      <div className="font-bold">{receipt.date} (Daily Cron)</div>
                      <div className="text-[10px] text-[#71717a]">{receipt.ci_suites.split(' ')[0]} Suites</div>
                    </div>
                  </div>
                  <span className="px-2 py-0.5 bg-[#052e16] text-[#34d399] border border-[#10b981]/30 font-bold text-[10px]">
                    {receipt.conclusion}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {/* Center & Right: Selected Merkle Receipt Inspector */}
          <div className="lg:col-span-2 bg-[#0a0a0a] border border-[#222222] p-5 flex flex-col">
            <div className="flex items-center justify-between border-b border-[#222222] pb-3 mb-4">
              <div className="flex items-center gap-2">
                <Shield className="w-4 h-4 text-[#10b981]" />
                <span className="font-mono text-xs font-bold text-[#ffffff]">
                  MERKLE RECEIPT // {selectedReceipt.date}
                </span>
              </div>
              <div className="flex items-center gap-2 font-mono text-[11px] text-[#10b981]">
                <Activity className="w-3.5 h-3.5" />
                <span>ALL 18 GATES PASSING</span>
              </div>
            </div>

            {/* Merkle Root Box */}
            <div className="bg-[#000000] border border-[#222222] p-3.5 mb-4 font-mono text-xs">
              <div className="text-[10px] text-[#71717a] uppercase mb-1 flex items-center gap-1">
                <Hash className="w-3 h-3 text-[#f59e0b]" />
                <span>SHA-256 Merkle Root Hash (Non-Repudiation Proof)</span>
              </div>
              <div className="text-[#f59e0b] break-all font-bold select-all">
                {selectedReceipt.merkle_root}
              </div>
            </div>

            {/* Criteria Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
              {/* AICPA SOC 2 Controls */}
              <div className="bg-[#000000] border border-[#222222] p-3">
                <div className="text-[11px] font-mono font-bold text-[#38bdf8] mb-2 flex items-center gap-1.5">
                  <Lock className="w-3 h-3" />
                  <span>AICPA Trust Services Criteria</span>
                </div>
                <ul className="space-y-1 text-[11px] font-mono text-[#a1a1aa]">
                  {selectedReceipt.tsc_controls.map((c, i) => (
                    <li key={i} className="flex items-center gap-1.5">
                      <CheckCircle2 className="w-3 h-3 text-[#10b981]" />
                      <span>{c}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* ISO 27001 Controls */}
              <div className="bg-[#000000] border border-[#222222] p-3">
                <div className="text-[11px] font-mono font-bold text-[#a78bfa] mb-2 flex items-center gap-1.5">
                  <Shield className="w-3 h-3" />
                  <span>ISO/IEC 27001:2022 ISMS</span>
                </div>
                <ul className="space-y-1 text-[11px] font-mono text-[#a1a1aa]">
                  {selectedReceipt.iso_controls.map((c, i) => (
                    <li key={i} className="flex items-center gap-1.5">
                      <CheckCircle2 className="w-3 h-3 text-[#10b981]" />
                      <span>{c}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Source Module Integrity Fingerprints */}
            <div className="bg-[#000000] border border-[#222222] p-3 font-mono text-xs">
              <div className="text-[10px] text-[#71717a] uppercase mb-2">
                Core Module Integrity Fingerprints (SHA-256)
              </div>
              <div className="space-y-1.5 text-[11px]">
                {selectedReceipt.source_fingerprints.map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between text-[#a1a1aa]">
                    <span className="text-[#ffffff] font-bold">{item.file}</span>
                    <span className="text-[#71717a] text-[10px]">{item.sha256}...</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
